apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-jupyter-dpl
spec:
  template:
    spec:      
      containers:
      - name: devops-jupyter      
        env:
          - name: JUPYTER_TOKEN
            value: io