apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: devops-jupyter-ingr
  #annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: devops-jupyter-svc
          servicePort: 8888
    