apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-jupyter-svcacc
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: ClusterRoleBinding
metadata:
  name: devops-admin-rb  
subjects:
- kind: ServiceAccount
  name: devops-jupyter-svcacc
  #namespace: devops
  #apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: cluster-admin  
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-jupyter-dpl
  labels:
    app: devops-jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-jupyter
  template:
    metadata:
      labels:
        app: devops-jupyter
    spec:
      serviceAccount: devops-jupyter-svcacc
      automountServiceAccountToken: true
      containers:
      - name: devops-jupyter
        image: mdnmdn/devops-notebook:latest      
        ports:
        - containerPort: 8888
          name: jupyter-port
        env:
          - name: JUPYTER_TOKEN
            value: io
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"          
---
apiVersion: v1
kind: Service
metadata:
  name: devops-jupyter-svc
spec:
  selector:
    app: devops-jupyter
  ports:
    - protocol: TCP
      port: 8888
      targetPort: jupyter-port

